spring:
  config:
    name: mysql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:myDb}
    username: rizwan
    password: P@ssw0rd1
  jpa:
    hibernate:
      ddl-auto: update
